<a href="https://colab.research.google.com/github/riteshyadav-345/MachineLearning/blob/main/Ch17_NaiveBayesClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('play_tennis.csv');

In [3]:
df.head()
df.drop(columns=['day'],inplace = True)

In [4]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [5]:
# p(Yes)
# p(No)

In [6]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [7]:
py=9/14
pn=5/14

In [8]:
py=9/14
pn=5/14
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [9]:
#Outlook
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [10]:
pon=0
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [11]:
#Temperature
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [12]:
pCoolNo =1/5
pHotNo = 2/5
pMildNo = 2/5

pCoolYes = 3/9
pHotYes = 2/9
pMildYes = 4/9

In [13]:
#Humidity
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [14]:
pHighNo=4/5
pNormalNo=1/5

pHighYes=3/9
pNormalYes=6/9

In [15]:
#Wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [16]:
pStrongNo=3/5
pWeakNo=2/5

pStrongYes=3/9
pWeakYes=6/9

In [17]:
#Outlook=sunny, Temp = Hot , Humidity = High, Wind =weak
#based on the given  cond find prob

In [18]:
pyes = py*psy*pHotYes*pHighYes*pWeakYes

In [19]:
print(pyes)

0.007054673721340388

In [20]:
pno = pn*psn*pHotNo*pHighNo*pWeakNo

In [21]:
print(pno)

0.02742857142857143

In [22]:
#NO PLAY